// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDys-RBpLqZQj0JBc2f9GW-JOlog3Da6cQ',
    appId: '1:372125687370:web:2db9f5bc6570d4191090b3',
    messagingSenderId: '372125687370',
    projectId: 'cs125-84277',
    authDomain: 'cs125-84277.firebaseapp.com',
    storageBucket: 'cs125-84277.appspot.com',
    measurementId: 'G-S68YRS4LWE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBubTYWPi4hTLBDVDriQH2G-l_yeUFfkeo',
    appId: '1:372125687370:android:a21cc69456d13efe1090b3',
    messagingSenderId: '372125687370',
    projectId: 'cs125-84277',
    storageBucket: 'cs125-84277.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKw4JjTBtJnVXnjMLPnMkO2IVHhWd5DH4',
    appId: '1:372125687370:ios:1a83e92b01528f1e1090b3',
    messagingSenderId: '372125687370',
    projectId: 'cs125-84277',
    storageBucket: 'cs125-84277.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKw4JjTBtJnVXnjMLPnMkO2IVHhWd5DH4',
    appId: '1:372125687370:ios:cdbe165965a8f1f21090b3',
    messagingSenderId: '372125687370',
    projectId: 'cs125-84277',
    storageBucket: 'cs125-84277.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
